{
 "title": "Region A - OpenStack Health Monitor - Public",
 "description": "https://github.com/SovereignCloudStack/openstack-health-monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "API calls",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^regiocloud/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      {
       "key": "cmd",
       "operator": "=~",
       "value": "/^^(nova|neutron|glance|cinder|token|catalog|swift|octavia)$/"
      },
      {
       "condition": "AND",
       "key": "method",
       "operator": "=~",
       "value": "/^^(boot|create|delete|floatingip-create|floatingip-delete|floatingip-list|image-show|issue|keypair-add|keypair-delete|keypair-list|lbaas-healthmonitor-create|lbaas-healthmonitor-delete|lbaas-listener-create|lbaas-listener-delete|lbaas-loadbalancer-create|lbaas-loadbalancer-delete|lbaas-loadbalancer-list|lbaas-loadbalancer-show|lbaas-member-create|lbaas-member-delete|lbaas-pool-create|lbaas-pool-delete|lbaas-pool-show|list|meta|net-create|net-delete|net-external-list|port-create|port-delete|port-list|port-show|port-update|router-create|router-delete|router-gateway-set|router-interface-add|router-interface-delete|router-show|router-update|security-group-create|security-group-delete|security-group-rule-create|show|subnet-create|subnet-delete)$/"
      }
     ]
    }
   ]
  },
  {
   "title": "API errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^regiocloud/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "cmd",
       "operator": "=~",
       "value": "/^^(nova|neutron|glance|cinder|token|catalog|swift|octavia)$/"
      },
      {
       "condition": "AND",
       "key": "method",
       "operator": "=~",
       "value": "/^^(boot|create|delete|floatingip-create|floatingip-delete|floatingip-list|image-show|issue|keypair-add|keypair-delete|keypair-list|lbaas-healthmonitor-create|lbaas-healthmonitor-delete|lbaas-listener-create|lbaas-listener-delete|lbaas-loadbalancer-create|lbaas-loadbalancer-delete|lbaas-loadbalancer-list|lbaas-loadbalancer-show|lbaas-member-create|lbaas-member-delete|lbaas-pool-create|lbaas-pool-delete|lbaas-pool-show|list|meta|net-create|net-delete|net-external-list|port-create|port-delete|port-list|port-show|port-update|router-create|router-delete|router-gateway-set|router-interface-add|router-interface-delete|router-show|router-update|security-group-create|security-group-delete|security-group-rule-create|show|subnet-create|subnet-delete)$/"
      }
     ]
    }
   ]
  },
  {
   "title": "API success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "API falis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^regiocloud/",
     "query": "SELECT ((count(\"return_code\")-sum(\"return_code\"))/count(\"return_code\")) FROM \"regiocloud\" WHERE (\"cmd\" =~ /^^(nova|neutron|glance|cinder|token|catalog|swift|octavia)$/ AND \"method\" =~ /^^(boot|create|delete|floatingip-create|floatingip-delete|floatingip-list|image-show|issue|keypair-add|keypair-delete|keypair-list|lbaas-healthmonitor-create|lbaas-healthmonitor-delete|lbaas-listener-create|lbaas-listener-delete|lbaas-loadbalancer-create|lbaas-loadbalancer-delete|lbaas-loadbalancer-list|lbaas-loadbalancer-show|lbaas-member-create|lbaas-member-delete|lbaas-pool-create|lbaas-pool-delete|lbaas-pool-show|list|meta|net-create|net-delete|net-external-list|port-create|port-delete|port-list|port-show|port-update|router-create|router-delete|router-gateway-set|router-interface-add|router-interface-delete|router-show|router-update|security-group-create|security-group-delete|security-group-rule-create|show|subnet-create|subnet-delete)$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "cmd",
       "operator": "=~",
       "value": "/^^(nova|neutron|glance|cinder|token|catalog|swift|octavia)$/"
      },
      {
       "condition": "AND",
       "key": "method",
       "operator": "=~",
       "value": "/^^(boot|create|delete|floatingip-create|floatingip-delete|floatingip-list|image-show|issue|keypair-add|keypair-delete|keypair-list|lbaas-healthmonitor-create|lbaas-healthmonitor-delete|lbaas-listener-create|lbaas-listener-delete|lbaas-loadbalancer-create|lbaas-loadbalancer-delete|lbaas-loadbalancer-list|lbaas-loadbalancer-show|lbaas-member-create|lbaas-member-delete|lbaas-pool-create|lbaas-pool-delete|lbaas-pool-show|list|meta|net-create|net-delete|net-external-list|port-create|port-delete|port-list|port-show|port-update|router-create|router-delete|router-gateway-set|router-interface-add|router-interface-delete|router-show|router-update|security-group-create|security-group-delete|security-group-rule-create|show|subnet-create|subnet-delete)$/"
      }
     ]
    }
   ]
  },
  {
   "title": "ssh conns",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^regiocloud/",
     "query": "SELECT count(\"return_code\") FROM \"regiocloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=", "value": "ssh" }
     ]
    }
   ]
  },
  {
   "title": "ssh errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^regiocloud/",
     "query": "SELECT sum(\"return_code\") FROM \"regiocloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=", "value": "ssh" }
     ]
    }
   ]
  },
  {
   "title": "ssh success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "API falis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "regiocloud",
     "query": "SELECT ((count(\"return_code\")-sum(\"return_code\"))/count(\"return_code\")) FROM \"regiocloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "cmd",
       "operator": "=~",
       "value": "/^^(nova|neutron|glance|cinder|token|catalog|swift|octavia)$/"
      },
      {
       "condition": "AND",
       "key": "method",
       "operator": "=~",
       "value": "/^^(boot|create|delete|floatingip-create|floatingip-delete|floatingip-list|image-show|issue|keypair-add|keypair-delete|keypair-list|lbaas-healthmonitor-create|lbaas-healthmonitor-delete|lbaas-listener-create|lbaas-listener-delete|lbaas-loadbalancer-create|lbaas-loadbalancer-delete|lbaas-loadbalancer-list|lbaas-loadbalancer-show|lbaas-member-create|lbaas-member-delete|lbaas-pool-create|lbaas-pool-delete|lbaas-pool-show|list|meta|net-create|net-delete|net-external-list|port-create|port-delete|port-list|port-show|port-update|router-create|router-delete|router-gateway-set|router-interface-add|router-interface-delete|router-show|router-update|security-group-create|security-group-delete|security-group-rule-create|show|subnet-create|subnet-delete)$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Resrcs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^regiocloud/",
     "query": "SELECT count(\"return_code\") FROM \"regiocloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^^wait/" }
     ]
    }
   ]
  },
  {
   "title": "Resrc errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^regiocloud/",
     "query": "SELECT sum(\"return_code\") FROM \"regiocloud\" WHERE (\"cmd\" = 'ssh') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^^wait/" }
     ]
    }
   ]
  },
  {
   "title": "iperf success rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "API falis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "regiocloud",
     "query": "SELECT ((count(\"return_code\")-sum(\"return_code\"))/count(\"return_code\")) FROM \"regiocloud\" WHERE (\"cmd\" = 'iperf3') AND $timeFilter",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "cmd",
       "operator": "=~",
       "value": "/^^(nova|neutron|glance|cinder|token|catalog|swift|octavia)$/"
      },
      {
       "condition": "AND",
       "key": "method",
       "operator": "=~",
       "value": "/^^(boot|create|delete|floatingip-create|floatingip-delete|floatingip-list|image-show|issue|keypair-add|keypair-delete|keypair-list|lbaas-healthmonitor-create|lbaas-healthmonitor-delete|lbaas-listener-create|lbaas-listener-delete|lbaas-loadbalancer-create|lbaas-loadbalancer-delete|lbaas-loadbalancer-list|lbaas-loadbalancer-show|lbaas-member-create|lbaas-member-delete|lbaas-pool-create|lbaas-pool-delete|lbaas-pool-show|list|meta|net-create|net-delete|net-external-list|port-create|port-delete|port-list|port-show|port-update|router-create|router-delete|router-gateway-set|router-interface-add|router-interface-delete|router-show|router-update|security-group-create|security-group-delete|security-group-rule-create|show|subnet-create|subnet-delete)$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_cmd $tag_method",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" }
     ],
     "measurement": "/^regiocloud/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "cmd",
       "operator": "=~",
       "value": "/^^(nova|neutron|glance|cinder|token|catalog|swift|octavia)$/"
      },
      {
       "condition": "AND",
       "key": "method",
       "operator": "=~",
       "value": "/^^(boot|create|delete|floatingip-create|floatingip-delete|floatingip-list|image-show|issue|keypair-add|keypair-delete|keypair-list|lbaas-healthmonitor-create|lbaas-healthmonitor-delete|lbaas-listener-create|lbaas-listener-delete|lbaas-loadbalancer-create|lbaas-loadbalancer-delete|lbaas-loadbalancer-list|lbaas-loadbalancer-show|lbaas-member-create|lbaas-member-delete|lbaas-pool-create|lbaas-pool-delete|lbaas-pool-show|list|meta|net-create|net-delete|net-external-list|port-create|port-delete|port-list|port-show|port-update|router-create|router-delete|router-gateway-set|router-interface-add|router-interface-delete|router-show|router-update|security-group-create|security-group-delete|security-group-rule-create|show|subnet-create|subnet-delete)$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "$tag_cmd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^regiocloud/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^^wait/" }
     ]
    }
   ]
  },
  {
   "title": "Bench (ssh) errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "ERR($tag_cmd)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" }
     ],
     "measurement": "/^regiocloud/",
     "select": [
      [
       { "params": [ "return_code" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "cmd",
       "operator": "=~",
       "value": "/^^(4000pi|iperf3|ssh|totDur|LBconn)$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API response times",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_cmd $tag_method",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^regiocloud/",
     "query": "SELECT \"duration\" FROM \"regiocloud\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "cmd",
       "operator": "=~",
       "value": "/^^(nova|neutron|glance|cinder|token|catalog|swift|octavia)$/"
      },
      {
       "condition": "AND",
       "key": "method",
       "operator": "=~",
       "value": "/^^(boot|create|delete|floatingip-create|floatingip-delete|floatingip-list|image-show|issue|keypair-add|keypair-delete|keypair-list|lbaas-healthmonitor-create|lbaas-healthmonitor-delete|lbaas-listener-create|lbaas-listener-delete|lbaas-loadbalancer-create|lbaas-loadbalancer-delete|lbaas-loadbalancer-list|lbaas-loadbalancer-show|lbaas-member-create|lbaas-member-delete|lbaas-pool-create|lbaas-pool-delete|lbaas-pool-show|list|meta|net-create|net-delete|net-external-list|port-create|port-delete|port-list|port-show|port-update|router-create|router-delete|router-gateway-set|router-interface-add|router-interface-delete|router-show|router-update|security-group-create|security-group-delete|security-group-rule-create|show|subnet-create|subnet-delete)$/"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource wait",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_cmd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^regiocloud/",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cmd", "operator": "=~", "value": "/^^wait/" }
     ]
    }
   ]
  },
  {
   "title": "Bench",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_cmd",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cmd" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^regiocloud/",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "cmd",
       "operator": "=~",
       "value": "/^^(4000pi|iperf3|ssh|totDur|LBconn)$/"
      }
     ]
    }
   ]
  }
 ]
}